
r.out.gdal input=ISTR_CmCost_Parecag_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Parecag_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Dragonja_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Dragonja_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Humagum_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Humagum_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Emonia_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Emonia_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Ad_Ningum_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Ad_Ningum_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Parentium_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Parentium_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Pola_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Pola_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Nesactium_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Nesactium_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Arsia_fl__30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Arsia_fl__30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Albona_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Albona_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Flanona_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Flanona_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Castra_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Castra_30m"  format=GTiff
r.out.gdal input=ISTR_CmCost_Ruginium_30m@PERMANENT output="C:\Users\amcle\OneDrive - icac.cat\Old Onedrive Stuff\Articles and Papers\CT LCP Istria Katarina\Data\Config\Code\Istria_mobility_analyses_R\Data\Output\Cost_corridors\Cumulative_cost_rasters\ISTR_CmCost_Ruginium_30m"  format=GTiff